"""add report

Revision ID: a13f5591d9d6
Revises: ab09456d8fe2
Create Date: 2025-03-15 22:22:06.203679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a13f5591d9d6'
down_revision: Union[str, None] = 'ab09456d8fe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblreports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reportguid', sa.UUID(), nullable=False),
    sa.Column('ideaid', sa.Integer(), nullable=False),
    sa.Column('reportedby', sa.Integer(), nullable=False),
    sa.Column('reportedreason', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ideaid'], ['tblideas.id'], ),
    sa.ForeignKeyConstraint(['reportedby'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reportguid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblreports')
    # ### end Alembic commands ###
