"""db commit

Revision ID: ab09456d8fe2
Revises: 
Create Date: 2025-03-15 22:17:46.059487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab09456d8fe2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_departments_name'), ['name'], unique=True)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tblcategories',
    sa.Column('categoryid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('categoryname', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('categoryid')
    )
    op.create_table('tbluserotp',
    sa.Column('colotpid', sa.Integer(), nullable=False),
    sa.Column('coluserid', sa.Integer(), nullable=False),
    sa.Column('colotp', sa.String(length=6), nullable=True),
    sa.Column('colisused', sa.Boolean(), nullable=True),
    sa.Column('colexpiresat', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('colotpid')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=True),
    sa.Column('lastname', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('default_pwd', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('isdisabled', sa.Boolean(), nullable=True),
    sa.Column('islocked', sa.Boolean(), nullable=True),
    sa.Column('lastlogin', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tblideas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ideaguid', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('thumbnail', sa.LargeBinary(), nullable=True),
    sa.Column('postedby', sa.Integer(), nullable=False),
    sa.Column('postedon', sa.Date(), nullable=False),
    sa.Column('ispostedanon', sa.Boolean(), nullable=False),
    sa.Column('isactived', sa.Boolean(), nullable=False),
    sa.Column('isreported', sa.Boolean(), nullable=True),
    sa.Column('categoryid', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoryid'], ['tblcategories.categoryid'], ),
    sa.ForeignKeyConstraint(['postedby'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ideaguid')
    )
    op.create_table('tblfiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fileguid', sa.UUID(), nullable=False),
    sa.Column('ideaid', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('filelocation', sa.String(length=500), nullable=True),
    sa.Column('filetype', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ideaid'], ['tblideas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fileguid')
    )
    op.create_table('tblideacomments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('commentuid', sa.UUID(), nullable=False),
    sa.Column('ideaid', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('postedby', sa.Integer(), nullable=False),
    sa.Column('postedon', sa.Date(), nullable=True),
    sa.Column('ispostedanon', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ideaid'], ['tblideas.id'], ),
    sa.ForeignKeyConstraint(['postedby'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commentuid')
    )
    op.create_table('tblidealikes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('likeuid', sa.UUID(), nullable=False),
    sa.Column('ideaid', sa.Integer(), nullable=False),
    sa.Column('isliked', sa.Boolean(), nullable=True),
    sa.Column('isdisliked', sa.Boolean(), nullable=True),
    sa.Column('postedby', sa.Integer(), nullable=False),
    sa.Column('postedon', sa.Date(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ideaid'], ['tblideas.id'], ),
    sa.ForeignKeyConstraint(['postedby'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('likeuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblidealikes')
    op.drop_table('tblideacomments')
    op.drop_table('tblfiles')
    op.drop_table('tblideas')
    op.drop_table('users')
    op.drop_table('tbluserotp')
    op.drop_table('tblcategories')
    op.drop_table('roles')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_name'))
        batch_op.drop_index(batch_op.f('ix_departments_id'))

    op.drop_table('departments')
    # ### end Alembic commands ###
